config/routes.rb
Rails.application.routes.draw do

  root 'groups#index'
  get 'attendances/date'

  resources :groups
  resources :students
  resources :attendances

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/attendance.rb
class Attendance < ApplicationRecord
  belongs_to :student

  validates :att_status, presence: { message: "Status Must Be Given" }

  groups_list =[]
  courses = []
  group = Group.all

  # find list of students
  group.each do |g|
    g.students.each do |student|
      output = "#{student.id} - #{student.name}"
      courses.push output
    end
  end

  STUDENT_LIST = courses


end

app/models/group.rb
class Group < ApplicationRecord

  has_many :students, :dependent => :delete_all

  #Setting up data validation so no fields can be left blank and ensures that
  #the end date comes after the start date.
  validates :name, presence: { message: "Name Must Be Given" }
  validates :stream, presence: { message: "Stream Must Be Given" }
  validates :startdate, presence: { message: "Start Date Must Be Given" }
  validates :enddate, presence: { message: "End Date Must Be Given" }
  validates :enddate, date: { after_or_equal_to: :startdate, message: "The End Date Given Must Be After The Start Date Given"}

  #Method that sets up connection to the database
  def self.open_conection
    conn=PG.connect( dbname: 'attendance_application_development')
  end

  #Selects groups from the database and orders them by name
  def self.sort_by_name
    conn = self.open_conection

    sql = "SELECT * FROM groups ORDER BY name"
    result = conn.exec(sql)

    group = result.map do |group|
      self.hydrate group
    end

    group
  end

  #Selects groups from the database and orders them by active groups
  def self.sort_by_active
    conn = self.open_conection

    sql = "SELECT * FROM groups ORDER BY active DESC"
    result = conn.exec(sql)

    group = result.map do |group|
      self.hydrate group
    end

    group
  end

  #Selects groups from the database and orders them by ID
  def self.sort_by_id
    conn = self.open_conection

    sql = "SELECT * FROM groups ORDER BY id"
    result = conn.exec(sql)

    group = result.map do |group|
      self.hydrate group
   end

    group
  end

  #Converts the data from postgresql into usable information
  def self.hydrate group_data

    group = Group.new

    group.id = group_data['id']
    group.name = group_data['name']
    group.stream = group_data['stream']
    group.startdate = group_data['startdate']
    group.enddate = group_data['enddate']
    group.active = group_data['active']

    group

  end

  def capitalize_name
    self.name.capitalize!
  end

end

app/models/student.rb
class Student < ApplicationRecord
  # attr_accessible :name, :attendance_attributes
  belongs_to :group
  has_many :attendances, :dependent => :delete_all

accepts_nested_attributes_for :attendances, allow_destroy: true


 validates :name, presence: { message: "Must Be Given" }

  # Function used by students controller will return a list of courses. This is passed to the students form.
  def self.course_list_assign
    courses = []
    groups = Group.all

    groups.each do |group|
      output = "#{group.id} - #{group.name}"
      courses.push output
    end

    course_list = courses.reverse
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/attendances_controller.rb
class AttendancesController < ApplicationController

  def index
    @groups=Group.all
  end


  def show
  end

  def new

    $id = params[:group]
    @group = Group.find $id
    $date = params[:date]


    @attendance = Attendance.new

  end

  def edit
  end

  def create

    @attendance = Attendance.new attendance_params

    puts "ATTENADANCE: #{@attendance.att_status}"
    puts "ID: #{@attendance.student_id}"

    respond_to do |format|
      if @attendance.save
        format.html{redirect_back fallback_location: root_path}
      else
        format.html{redirect_back fallback_location: root_path}
      end
    end
  end

  def update
  end

  def destroy
    @attendance = Attendance.find params[:id]
    @attendance.destroy
    redirect_back fallback_location: root_path
  end

  def attendance_params
    attendance_params = params.require(:attendance).permit(:att_status, :date, :comment, :student_id)
  end
  
  def group_params
    group_params = params.require(:group).permit(:name)
  end

end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController

  def index

    #Selects groups fromt the database ordered by ID
    @groups = Group.sort_by_id

    #Selects groups fromt the database ordered by Name
    @groups1 = Group.sort_by_name

    #Selects groups fromt the database ordered by the group's active status
    @groups2 = Group.sort_by_active

  end

  def show
    @group = Group.find params[:id]
  end

  def new
    @group = Group.new
  end

  def edit
    @group = Group.find params[:id]
  end

  def create
    @group = Group.new group_params

    #Capitalises group name before saving allow sorting to work
    @group.capitalize_name

    respond_to do |format|

      #If the group can be saved you will be directed to the groups
      #and a message will appear saying it was updated
      if @group.save
        format.html{redirect_to @group, notice: "#{@group.name} was created"}
      #If the group can't be saved it will reload the new page.
      else
        format.html{render :new}
      end

    end

  end

  def update
    @group = Group.find params[:id]

    @group.capitalize_name

    respond_to do |format|
      if @group.update group_params
        format.html{redirect_to @group, notice: "#{@group.name} was updated"}
      else
        format.html{render :new}
      end
    end

  end

  def destroy
    @group = Group.find params[:id]
    @group.destroy
    redirect_to root_path
  end

  def group_params
    group_params = params.require(:group).permit(:name,:stream,:startdate,:enddate,:active)
  end


end

app/controllers/students_controller.rb
class StudentsController < ApplicationController

  #Select all of the students from the student section of the seed.rb
  # Select all groups from the group section within the seed.rb
  def index
    @students  = Student.all
    @group = Group.all
  end

  def show
    # Find the student by ID
    @student = Student.find params[:id]
    # Find the group a student belongs to via the group_id
    @group = Group.find (@student.group_id)
  end

  def new
    # Set selected group to new student
    @student = Student.new
    @course_list = Student.course_list_assign
  end

  def edit
    # Find student by ID and edit accordingly
    @student = Student.find params[:id]
    @course_list = Student.course_list_assign
  end

  def create
    # Create a new student, redirect to student index page and notify that student has been created
    @student = Student.new student_params
    @course_list = Student.course_list_assign
      respond_to do |format|
        if @student.save
          format.html{redirect_to @student, notice: "#{@student.name} was created"}
        else
          format.html{render :new}
        end
    end
  end

  def update
    # Update a new student, redirect to student index page and notify that student has been Updated
    @student = Student.find params[:id]
    @course_list = Student.course_list_assign
    respond_to do |format|
      if @student.update student_params
        format.html{redirect_to @student, notice: "'#{@student.name}' was updated"}
      else
        format.html{render :edit}
      end
    end
  end

  def destroy
    # Find student by ID, remove details when delete is selected and redirect to the student index page
    @student = Student.find params[:id]
    @student.destroy
    redirect_to students_path
  end

  def student_params
    student_params = params.require(:student).permit(:name, :active, :group_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/attendances_helper.rb
module AttendancesHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/jobs/application_job.rb
class ApplicationJob < ActiveJob::Base
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/views/attendances/index.html.erb
<h1>Add New Attendances</h1>

<!-- set the current date -->
<script type="text/javascript">
  var date = new Date();

  var day = date.getDate();
  var month = date.getMonth() + 1;
  var year = date.getFullYear();

  if (month < 10) month = "0" + month;
  if (day < 10) day = "0" + day;

  var today = year + "-" + month + "-" + day;
  $("#theDate").attr("value", today);
</script>

<center>
  <form id="myForm" action="/attendances/new" method="get" class="form att-form">
    <div class="field att_field select">
      <select name="group">
        <% @groups.each do |group| %>
        <% if group.active == true %>
          <option value="<%= group.id %>"><%= group.name %></option>
        <% end %>
        <% end %>
      </select>
    </div>
    <div class="field att_field nameInput">
      <input id="theDate" type="date" name="date" value="" />
    </div>
    <div class="action_button att_field">
      <button type="submit">Next</button>
    </div>
  </form>
</center>

app/views/attendances/new.html.erb
<h1>Attendances</h1>

<%= render 'layouts/att_form' %>

app/views/groups/_form.html.erb
<%= form_for group do |g| %>

<center>
<!-- Checks if there are already error messages. If there are any messages then
additonal ones will not show- However, if there are no messages already on the page
then messages will appear -->

<!-- In order for the alerts to be styles classes have been added -->
<% if group.errors.any? %>

<div class="alert alert-danger message-info" role="alert">
  <h2 class="alert-heading"> <%= pluralize(group.errors.count,'error') %> To Fix </h2>
  <hr>
  <% group.errors.each do |attr, message| %>
    <ul>
      <li style="list-style: none;">
        <% if message.to_s.length != 0 %>
          <p class="mb-0 message" role="alert"><%= message %></p>
        <% end %>
      </li>
    </ul>
  <% end %>
</div>

<% end %>

<div class="form">
  <div class="field">
    <%= g.label :Name %>
    <div class="nameInput">
      <%= g.text_field :name %>
    </div>
  </div>
  <br>
  <div class="field">
    <%= g.label :Stream %>
    <div class="nameInput">
      <%= g.text_field :stream %>
    </div>
  </div>
  <div class="field">
    <%= g.label :Start_Date %>
    <div class="nameInput">
      <%= g.date_field :startdate, :order => [:day, :month, :year]%>
    </div>
  </div>
  <div class="field">
    <%= g.label :End_Date %>
    <div class="nameInput">
      <%= g.date_field :enddate, :order => [:day, :month, :year] %>
    </div>
  </div>
  <div class="field">
    <%= g.label :Active %>
    <div class="select">
    <%= g.check_box :active %>
    </div>
  </div>
  <br>
  <div class="action">
      <%= g.submit  %>
  </div>
</div>
</center>

<% end %>

app/views/groups/edit.html.erb
<h1>Edit <%= @group.name %></h1>

<!-- Renders the form from the _form.html.erb -->
<%= render 'form', group: @group %>

app/views/groups/index.html.erb
<h1>Groups</h1>

<!-- Button's for sorting results -->
<div class="container">
  <div class="row">
    <div class="buttons-sort">
      <button type="button" name="button" id="sort_id" class="btn btn-secondary">Sort By Id</button>
      <button type="button" name="button" id="sort_name" class="btn btn-secondary" >Sort By Name</button>
      <button type="button" name="button" id="sort_active" class="btn btn-secondary">Sort By Active</button>
    </div>
  </div>
  <div class="row">
    <!-- This key shows blocks red and green -->
    <div class="buttons-sort">
      <p class="key"> Inactive</p>
      <%= image_tag("square_block_red.jpg", size: "20x20", alt: "Edit Entry", class: "key") %>

      <p class="key"> Active</p>
      <%= image_tag("square_block.png", size: "20x20", alt: "Edit Entry", class: "key") %>
    </div>
  </div>
</div>

<!-- Below is the cards- A new card is generated for each new group -->
<!-- Bootstrap container, row and col -->
<!-- Listed below is the name, stream, start and end date -->
<div class="" id="order_id">
  <div class="container">
    <div class="row group_info" id = "group_info">
      <% @groups.each do |group| %>
      <div class="col-md-4 col-sm-6 card-group">
        <%= link_to group_path(group), class: "link_style" do %>
        <!-- This adds the classes active-group if the group is active and the class inactive is there inactive -->
        <div class="group-card <%= group.active ? "active-group" : "inactive-group" %>">
          <h2><%= group.name %></h2>
          <ul class="list-group list-group-flush">
            <li class="list-group-item group-card-info">Stream: <%= group.stream %></li>
            <li class="list-group-item group-card-info">Start Date: <%= group.startdate %></li>
            <li class="list-group-item group-card-info">End Date: <%= group.enddate %></li>
          </ul>
        </div>
        <% end %>
      </div>
      <% end %>
    </div>
  </div>
</div>

<!-- Below is the cards- A new card is generated for each new group -->
<!-- Bootstrap container, row and col -->
<!-- Listed below is the name, stream, start and end date -->
<div class="" id="order_name">
  <div class="container">
    <div class="row">
      <% @groups1.each do |group| %>
      <div class="col-md-4 col-sm-6 card-group">
        <%= link_to group_path(group), class: "link_style" do %>
        <!-- This adds the classes active-group if the group is active and the class inactive is there inactive -->
        <div class="group-card <%= group.active ? "active-group" : "inactive-group" %>">
          <h2><%= group.name %></h2>
          <ul class="list-group list-group-flush">
            <li class="list-group-item group-card-info">Stream: <%= group.stream %></li>
            <li class="list-group-item group-card-info">Start Date: <%= group.startdate %></li>
            <li class="list-group-item group-card-info">End Date: <%= group.enddate %></li>
          </ul>
        </div>
        <% end %>
      </div>
      <% end %>
    </div>
  </div>
</div>

<!-- Below is the cards- A new card is generated for each new group -->
<!-- Bootstrap container, row and col -->
<!-- Listed below is the name, stream, start and end date -->
<div class="" id="order_active">
  <div class="container">
    <div class="row">
      <% @groups2.each do |group| %>
      <div class="col-md-4 col-sm-6 card-group">
        <%= link_to group_path(group), class: "link_style" do %>
        <!-- This adds the classes active-group if the group is active and the class inactive is there inactive -->
        <div class="group-card <%= group.active ? "active-group" : "inactive-group" %>">
          <h2><%= group.name %></h2>
          <ul class="list-group list-group-flush">
            <li class="list-group-item group-card-info">Stream: <%= group.stream %></li>
            <li class="list-group-item group-card-info">Start Date: <%= group.startdate %></li>
            <li class="list-group-item group-card-info">End Date: <%= group.enddate %></li>
          </ul>
        </div>
        <% end %>
      </div>
      <% end %>
    </div>
  </div>
</div>

<!-- Button for creating a new group -->
<div class="btn-new">
  <%= link_to "Add a Group", new_group_path, class: "btn btn-secondary new_group_button" %>
</div>

<script type="text/javascript">

  // Loads the page with the groups being shown ordered by ID
  $("#order_id").show()
  $("#order_name").hide();
  $("#order_active").hide();

  // Adds click event to the "sort by name" button to display the groups ordered by name
  document.getElementById("sort_name").addEventListener("click", function(){
    $("#order_name").show();
    $("#order_id").hide();
    $("#order_active").hide();
  });

  // Adds click event to the "sort by ID" button to display the groups ordered by ID
  document.getElementById("sort_id").addEventListener("click", function(){
    $("#order_name").hide();
    $("#order_id").show();
    $("#order_active").hide();
  });

  // Adds click event to the "sort by active" button to display the groups
  //ordered by acitve groups first
  document.getElementById("sort_active").addEventListener("click", function(){
    $("#order_name").hide();
    $("#order_id").hide();
    $("#order_active").show();
  });

  //Function to keep checking how the grouos are being displayed and highilght a button accordingly
  setInterval(function () {
    //Checks if the groups are displayed in name order
    if ($("#order_name").is(":visible")) {
      $("#sort_name").css({"background-color":"black", "color":"white"})
    } else {
      $("#sort_name").css({"background-color":"#6c757d", "color":"white"})
    }

    //Checks if the groups are displayed ID ordered by
    if ($("#order_active").is(":visible")) {
      $("#sort_active").css({"background-color":"black", "color":"white"})
    } else {
      $("#sort_active").css({"background-color":"#6c757d", "color":"white"})
    }

    //Checks if the groups are displayed with active groups being shown first
    if ($("#order_id").is(":visible")) {
      $("#sort_id").css({"background-color":"black", "color":"white"})
    } else {
      $("#sort_id").css({"background-color":"#6c757d", "color":"white"})
    }

  }, 10);

</script>

app/views/groups/new.html.erb
<h1>Add new Group</h1>

<!-- Renders the form from the _form.html.erb -->
<%= render 'form', group: @group %>

app/views/groups/show.html.erb
<!-- Prints the notice to indicate a new group has been made
Styles with CSS and Bootstrap
Checks if any notices are already on the page, if not then it will appear -->
<div class="alert-success" role="alert">
  <% if notice.to_s.length != 0 %>
    <p class="alert notice"><%= notice %></p>
  <% end %>
</div>

<!-- JS code to check if DataTables applied, if not then apply it to the students list. -->
<script type="text/javascript">
  $(document).on('turbolinks:load', function() {
      if (!document.getElementById("group-attendance_wrapper")) {
        $('#group-attendance').DataTable();
      }
  });
</script>

<div class="container">
<!-- Displays the groups name, start and end date, whether they are active and their stream -->
  <div class="row">
    <div class="col-md-12 group-container attend_group">
      <center>
      <h1>Attendance for: <%= @group.name %></h1>
      <ul>
        <li>Start date: <%= @group.startdate %></li>
        <li>End date: <%= @group.enddate %></li>
        <li>Active: <%= @group.active %></li>
        <li>Stream: <%= @group.stream %></li>
      </ul>

<!-- Buttons to edit and delete that particular group -->
      <%= link_to "Edit Group", edit_group_path, class: "btn btn-primary"%>
      <button type="button" class="btn btn-danger" data-toggle="modal" data-target="#deleteConfirmModal">
        Delete Group
      </button>

<!-- Model appears displaying a message to confirm if the group to be deleted -->
      <div class="modal fade" id="deleteConfirmModal" tabindex="-1" role="dialog" aria-labelledby="deleteConfirmTitle" aria-hidden="true">
        <div class="modal-dialog" role="document">
          <div class="modal-content">
            <div class="modal-header">
              <h5 class="modal-title" id="deleteConfirmTitle">Are you sure?</h5>
              <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
              </button>
            </div>
            <div class="modal-body">
              <b>This will also delete all the students in the group</b>
            </div>
            <!-- If user clicks confirm then it will delete all from the database -->
            <div class="modal-footer">
              <%= link_to 'Delete Group', @group, method: :delete, class: "btn btn-danger"%>
              <button type="button" class="btn btn-primary" data-dismiss="modal">Close</button>
            </div>
          </div>
        </div>
      </div>

    </center>
    </div>
  </div>
</div>

  <div class="container">
    <table id="group-attendance" class="table table-bordered table-hover">
      <thead>
        <tr>
          <th scope="col">#</th>
          <th scope="col">Student</th>
          <th scope="col">On Time</th>
          <th scope="col">< 5 mins</th>
          <th scope="col">> 5 mins</th>
          <th scope="col">Authorised</th>
          <th scope="col">Unauthorised</th>
        </tr>
      </thead>
      <tbody>

        <% @group.students.each do |student| %>

        <% att_array = [0, 0, 0, 0, 0]
        percArray = [0, 0, 0, 0, 0] %>

        <tr>
          <% student.attendances.each do |attendance| %>

          <%

          case attendance.att_status
          when 1
            att_array[0] += 1
          when 2
            att_array[1] += 1
          when 3
            att_array[2] += 1
          when 4
            att_array[3] += 1
          when 5
            att_array[4] += 1
          end

          %>

          <% end %>

          <%

          sum = 0.0

          att_array.each do |value|
            sum+=value
          end

          percArray[0] = ((att_array[0] / sum) * 100).round 2
          percArray[1] = ((att_array[1] / sum) * 100).round 2
          percArray[2] = ((att_array[2] / sum) * 100).round 2
          percArray[3] = ((att_array[3] / sum) * 100).round 2
          percArray[4] = ((att_array[4] / sum) * 100).round 2

          %>
          <td><b><%= student.id %></b></td>
          <td><%= link_to "#{student.name.titlecase}", student %></td>

          <% percArray.each do |p| %>

            <% if p.nan? %>
              <td>0.0%</td>
            <% else %>
              <td><%= p %>%</td>
            <% end %>

          <% end %>

        </tr>
        <% end %>

      </tbody>
    </table>

  </div>


</div>

app/views/layouts/_att_form.html.erb
<center>
<% status = ["On time", "Late by <5 minutes", "Late by >5 minutes", "Authorised Absence", "Unauthorised Absence"] %>

<%= form_for @attendance do |g| %>

<% if @attendance.errors.any? %>
<div class="alert alert-danger message-info" role="alert">
  <h2 class="alert-heading"> <%= pluralize(@attendance.errors.count,'error') %> To Fix </h2>
  <hr>
  <% @attendance.errors.each do |attr, message| %>
    <ul>
      <li style="list-style: none;">
        <% if message.to_s.length != 0 %>
          <p class="mb-0 message" role="alert"><%= message %></p>
        <% end %>
      </li>
    </ul>
  <% end %>
</div>
<% end %>

  <!-- sets up some values-->
  <% student_list = [] %>
  <% group = @group %>

  <!-- sets the date to the date entered on the previous page -->
  <%= g.hidden_field :date, value: $date %>


  <div class="att_form form">

    <!-- logic to show students or not -->
    <% group.students.each do |student| %>
      <% exists = false %>
      <% example = student.attendances.where("date = '#{$date}'") %>
      <% puts "date: #{$date}" %>
      <% unless example.empty? %>
        <% exists = true %>
      <% end %>
      <!-- only show students if they are active or they dont have an attendance for that date -->
      <% unless exists == true || student.active == false %>
        <% output = "#{student.id} - #{student.name}" %>
        <% student_list.push output %>
      <% end %>
    <% end %>

    <!-- display group name -->
    <h2><%= link_to "#{@group.name}", group_path(@group) %> </h2>
    <br>

    <div class="select att_field">
      <!-- drop down list for each student and collects the students id -->
      <%= g.select(:student_id, student_list) %>
    </div>
    <div class="radio_buttons att_field">
      <%= g.collection_radio_buttons :att_status, (1..5).map{|n| [n, status[n-1]]}, :first, :last, :class => "col-12 form-control" %>
    </div>
    <div class="field att_field">
      <%= g.label :comment %>
      <%= g.text_field :comment %>
    </div>

  <div class="action att_field">
    <%= g.submit %>
  </div>
</div>
<% end %>
</center>

app/views/layouts/_footer.html.erb
<nav class="navbar navbar-dark bg-dark footer-fixed">
  <span class="navbar-brand">Attendance Application <small>&copy; Sparta Global</small></span>
  <a href="#headers" class="footer-link">Back To Top</a>
</nav>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark" id="headers">
  <a class="navbar-brand" href="/">
    <%= image_tag("sparta.jpg", size: "40x40", alt: "Nav Logo") %>
  </a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNavDropdown">
    <ul class="navbar-nav">
      <li class="nav-item">
        <!-- <%= link_to "Home", groups_path %> -->
        <a class="nav-link" href="/">Home</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="<%= students_path %>">Students</a>
      </li>
      <span class="verticalLine"></span>
      <li class="nav-item">
        <a class="nav-link" href="<%= new_group_path %>">Add New Group</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="<%= new_student_path %>">Add New Student</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="<%= attendances_path %>">Add Attendance</a>
      </li>
    </ul>
  </div>
</nav>

app/views/students/_form.html.erb
<%= form_for student do |p| %>

<center>
  <% if student.errors.any? %>
  <div class="alert alert-danger message-info" role="alert">
    <h2 class="alert-heading"><%= pluralize(student.errors.count, 'error') %> To Fix </h2>
    <hr>
      <% student.errors.full_messages.each do |message| %>
      <ul>
        <li style="list-style: none;">
          <p class="mb-0 message" role="alert"> <%= message %> </p>
        </li>
      </ul>
    <% end %>
  </div>
  <% end %>
  <br>
  <center>
  <!-- A text field for the user to input the students name -->
  <div class="form">
    <div class="field">
      <%= p.label :name %>
      <div class="nameInput">
        <%= p.text_field :name %>
      </div>
    </div>
    <br>
    <!-- A select field for the user to select the students course  -->
    <div class="field">
      <%= p.label :group_id %>
      <div class="select">
        <%= p.select(:group_id, @course_list) %> <!-- @course_list can be found in the students.rb file -->
      </div>
    </div>
    <!-- A checkbox that allows the user to tick a box to state whether the student is on the course or not -->
    <div class="field">
      <%= p.label :active %>
      <%= p.check_box :active %>
    </div>
    <br>
    <div class="action">
      <%= p.submit "Submit" %>
    </div>
  </div>
</center>
<% end %>

app/views/students/edit.html.erb
<h1>Edit: <%= @student.name %> </h1>
<%= render "form", student: @student %>

app/views/students/index.html.erb
<!-- JS code to check if DataTables applied, if not then apply it to the students list. -->
<script type="text/javascript">
  $(document).on('turbolinks:load', function() {
      if (!document.getElementById("studentslist_wrapper")) {
        $('#studentslist').DataTable();
      }
  });
</script>

<div class="container">
  <h1 class="list-h1" >Students</h1>
  <table id="studentslist" class="list-table table table-hover table-bordered">
    <thead>
      <tr>
        <th scope"col">#</th>
        <th scope"col">Name</th>
        <th scope"col">Active</th>
        <th scope"col">Stream</th>
        <th scope"col">Group</th>
      </tr>
    </thead>
    <tbody>
      <% @students.each do |student| %>
        <tr>
          <th scope="row"><%= student.id %></th>
          <td><%= link_to "#{student.name.titlecase}", student %></td>
          <td>
            <%if student.active == true %>
              <span class="badge badge-success"> Active </span>
            <% else %>
              <span class="badge badge-secondary"> Inactive </span>
            <% end %>
          </td>
          <td><span class="badge badge-info"><%= @group.find(student.group_id).stream.upcase%></span></td>
          <td>
          <%= link_to "#{@group.find(student.group_id).name.upcase}", @group.find(student.group_id), class: "badge badge-info" %></td>
        </tr>
      <% end %>

      <br>
      <br>
    </tbody>
  </table>
  <div class="new_student actions-list">
    <%= link_to 'Create a new student', new_student_path, class: "btn btn-primary" %>
  </div>
</div>

app/views/students/new.html.erb
<h1>Add a new Student</h1>
<%= render "form", student: @student %>